application: mk10koers
version: 1
runtime: python
api_version: 1

handlers:
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin  
  
- url: /static
  static_dir: static
  
- url: /js
  static_dir: js  
  
- url: /img
  static_dir: img
  
- url: /css
  static_dir: css

- url: /.*
  script: main.py

